storePassword=yogadimashotelio123store
keyPassword=yogadimashotelio123key
keyAlias=yogadimashotelio
storeFile=C:/Users/User/FlutterDeployment/hotelio/UsersUserFlutterDeploymenthoteliohotelio-upload-keystore.jks