// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXr67rNvBTdsMvl5zbIljR-VaZNItfcRw',
    appId: '1:380670514801:web:b8ecb7b671c6a4a31e6dd0',
    messagingSenderId: '380670514801',
    projectId: 'course-hotelio-50f61',
    authDomain: 'course-hotelio-50f61.firebaseapp.com',
    storageBucket: 'course-hotelio-50f61.appspot.com',
    measurementId: 'G-JJ6P1RKWHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqYge5pNUOwX9RyHoGDCgTNziZjThKk8w',
    appId: '1:380670514801:android:9af92cbac686d5391e6dd0',
    messagingSenderId: '380670514801',
    projectId: 'course-hotelio-50f61',
    storageBucket: 'course-hotelio-50f61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvZT79xic8YX7GPFQmMSHzrROCydwEW6s',
    appId: '1:380670514801:ios:1b5b6bf61346ddff1e6dd0',
    messagingSenderId: '380670514801',
    projectId: 'course-hotelio-50f61',
    storageBucket: 'course-hotelio-50f61.appspot.com',
    iosBundleId: 'com.yogadimas.hotelio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvZT79xic8YX7GPFQmMSHzrROCydwEW6s',
    appId: '1:380670514801:ios:3a0788f2aac56a111e6dd0',
    messagingSenderId: '380670514801',
    projectId: 'course-hotelio-50f61',
    storageBucket: 'course-hotelio-50f61.appspot.com',
    iosBundleId: 'com.yogadimas.courseHotelio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXr67rNvBTdsMvl5zbIljR-VaZNItfcRw',
    appId: '1:380670514801:web:af7152519fa63d8a1e6dd0',
    messagingSenderId: '380670514801',
    projectId: 'course-hotelio-50f61',
    authDomain: 'course-hotelio-50f61.firebaseapp.com',
    storageBucket: 'course-hotelio-50f61.appspot.com',
    measurementId: 'G-F6G2EHEN57',
  );
}
